server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        # Auth endpoints handled by Credit Service
        - id: auth-endpoints
          uri: lb://microservice-credit-application-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        
        # Credit Service - For affiliates and analysts
        - id: credit-service
          uri: lb://microservice-credit-application-service
          predicates:
            - Path=/api/credit/**
          filters:
            - StripPrefix=1
        
        # Risk Service - For analysts and admins
        - id: risk-service
          uri: lb://microservice-risk-central-service
          predicates:
            - Path=/api/risk/**
          filters:
            - StripPrefix=1
        
        # Swagger UI for Credit Service (includes Auth + Credit + Affiliates)
        - id: credit-swagger-ui
          uri: lb://microservice-credit-application-service
          predicates:
            - Path=/swagger-ui.html, /swagger-ui/**, /v3/api-docs/**, /swagger-resources/**
          filters:
            - RewritePath=/swagger-ui.html, /swagger-ui/index.html

# JWT Configuration (must match auth service)
jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.riwi.microservice.gateway: DEBUG
