eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        # Auth Service - Public endpoints
        - id: auth-service-public
          uri: lb://microservice-auth
          predicates:
            - Path=/api/auth/login, /api/auth/register, /api/auth/validate
          filters:
            - StripPrefix=1
        
        # Auth Service - Protected endpoints
        - id: auth-service-protected
          uri: lb://microservice-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        
        # Credit Service - For affiliates and analysts
        - id: credit-service
          uri: lb://microservice-credit-application-service
          predicates:
            - Path=/api/credit/**
          filters:
            - StripPrefix=1
        
        # Risk Service - For analysts and admins
        - id: risk-service
          uri: lb://microservice-risk-central-service
          predicates:
            - Path=/api/risk/**
          filters:
            - StripPrefix=1

# JWT Configuration (must match auth service)
jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.riwi.microservice.gateway: DEBUG
